"""
Example utterances used by the semantic intent router.
"""

TOOLS = {
    "image_to_pdf": [
        "combine these images and create a pdf",
        "combine images into pdf",
        "create pdf from pictures",
        "make pdf using photos",
        "put these images into one document",
        "convert these images to pdf",
        "turn these pictures into a pdf",
        "bundle my photos into one pdf",
    ],
    "convert_to_pdf": [
        "turn this document into pdf",
        "convert this file to pdf",
        "save this as pdf",
        "export this document to pdf",
        "make a pdf from this file",
        "generate a pdf version",
        "convert this document into a pdf",
        "create pdf from this document",
    ],
    "merge_pdf": [
        "merge these pdf files",
        "combine documents",
        "join these pdfs",
        "put these pdf files together",
        "combine all these files into one pdf",
        "stitch these pdfs together",
        "merge the attached pdfs",
        "create one pdf from these pdf files",
    ],
    "split_pdf": [
        "split this pdf into pages",
        "separate the pages of this pdf",
        "break this document into pages",
        "split this document page by page",
        "make one file per page",
        "divide this pdf into separate pages",
        "split this pdf",
        "separate this document into multiple pdfs",
    ],
    "compress_pdf": [
        "compress this pdf",
        "make this pdf smaller",
        "reduce pdf file size",
        "optimize this document",
        "shrink this pdf",
        "reduce the size of this pdf",
        "compress the attached pdf",
        "make this file lighter",
    ],
    "extract_text": [
        "extract text from this document",
        "get text from this file",
        "read this pdf",
        "pull out all text from this document",
        "ocr this file",
        "grab the text from this image",
        "read the words in this document",
        "extract the written content",
    ],
    "pdf_to_images": [
        "convert this pdf to images",
        "convert pdf pages to images",
        "save pdf as pictures",
        "turn pdf into images",
        "extract images from pdf pages",
        "export each pdf page as an image",
        "make pngs from this pdf",
        "convert this document into page images",
    ],
    "delete_pages": [
        "delete pages from this pdf",
        "remove pages 2 and 3",
        "drop the first page",
        "omit pages 4 to 6",
        "remove selected pages",
        "delete these pages from the document",
        "take out page 1",
        "exclude page 5",
    ],
    "rotate_pdf": [
        "rotate this pdf",
        "turn this document 90 degrees",
        "rotate the pages clockwise",
        "change the orientation of this pdf",
        "spin this document",
        "rotate this file to the left",
        "make this pdf landscape",
        "turn this page upside down",
    ],
    "add_watermark": [
        "add a watermark to this pdf",
        "stamp this document",
        "mark this pdf as confidential",
        "put a watermark on every page",
        "brand this pdf",
        "add logo text to this document",
        "watermark this file",
        "mark every page with confidential",
    ],
    "create_zip": [
        "zip these files",
        "create an archive from these documents",
        "package these files together",
        "bundle everything into a zip",
        "compress these files into an archive",
    ],
    "extract_zip": [
        "extract this zip",
        "unzip these files",
        "open this archive",
        "unpack the zip file",
        "extract the archive contents",
    ],
    "pdf_to_word": [
        "convert this pdf to word",
        "turn this pdf into a docx file",
        "save this pdf as a word document",
        "export this pdf to docx",
        "make a doc file from this pdf",
    ],
    "extract_pages": [
        "extract pages 1 to 3",
        "keep only pages 2 and 4",
        "save page 1 as a new pdf",
        "pull out selected pages from this pdf",
        "extract pages 3-5 into one file",
    ],
    "text_to_pdf": [
        "turn this text into a pdf",
        "create a pdf from this text",
        "make a pdf from the text I wrote",
        "save this text as pdf",
        "convert my text into a document",
    ],
}
